space_before_fn_sig_paren = true
binop_separator = "Front"
reorder_imports = false
reorder_modules = false
match_block_trailing_comma = false
merge_derives = true
merge_imports = true
fn_params_layout = "Compressed"
trailing_comma = "Never"
ignore = ['./src/schema.rs', './src/task_item.rs']
