version: '3.8'
services:
   db:
      image: "postgres:11.8"
      ports:
         - "5433:5432"
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      volumes: db-data
   app:
      build:
         context: ./
         dockerfile: Dockerfile
      depends_on:
         - db
      command: sh -c "./wait-for.sh db:5432 -- todo_service" # embed migrations, diesel is not portable enough for this.
      volumes:
         - .:/src
      ports:
         - "${SERVICE_PORT}:8080"
      environment:
         - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
volumes:
   db-data:
      driver: local


