use std::str::FromStr;

grammar;

pub Date: Vec<u32> = {
    <day:Day> => vec![day],
    <month:Month> "-" <day:Day> => vec![month, day],
    <month:Month> "-" <day:Day> "-" <year:Year> => vec![month, day, year],
}

Num: u32 = {
    r"[0-9]{2}" => u32::from_str(<>).unwrap()
}

Day: u32 = {
    r"[0-2][0-9]|3[01]" => u32::from_str(<>).unwrap()
}

Month: u32 = {
    r"1[0-2]|[0-9]" => u32::from_str(<>).unwrap()
}

Year: u32 = {
    r"'\d{2}|\d{4}" => u32::from_str(<>).unwrap()
}
